[package]
name = "nested_dir_file_copy"
version = "0.3.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2.3.2"
clap = { version = "3.0.10", features = ["derive"] }
